[[links]]
label = "Email"
url = "mailto:mail@blakenelson.me"
display = "mail@blakenelson.me"

[[links]]
label = "GitHub"
url = "https://github.com/NelsonBlakeN"
display = "github.com/NelsonBlakeN"

[[links]]
label = "LinkedIn"
url = "https://linkedin.com/in/blakenelson19"
display = "linkedin.com/in/blakenelson19"
